### ISSUE TITLE
sqlinjection

### ISSUE THREAD

**Issue by victorb** [ipfspics/server#1]
Seems there are some possibilities for people to do injections.

https://github.com/ipfspics/server/blob/master/preview.php#L21

$hash is coming directly from `$_GET` which is no good.

**Comment by cloutier** [comment]
[The code exits](http://ipfs.pics/preview.php?hash=Qwaef%27a%3E%3Cawef) if someone tries to input something that isn't a valid IPFS hash. 

```
    if (preg_match('/^([A-z0-9])+$/', $_GET['hash']) ) {
        $hash = $_GET['hash'];
    } else {
        exit("wrong hash");
    }
```

I know it's maybe not the cleanest way to do this. I really need to add comments to the code. 
HTML code is also properly escaped in the albums.

Thanks a lot for checking our code though :smile:  it really helps us!

**Comment by victorb** [comment]
Ah, my bad for missing that! Thanks for the quick reply though!
