### ISSUE TITLE
ipfs api calls

### ISSUE THREAD

**Issue by whyrusleeping** [ipfspics/server#12]
Hey guys!
I was reading through a bit of code, and I think you guys would be better off using [the javascript ipfs api bindings](https://github.com/ipfs/node-ipfs-api) instead of calling a fairly costly exec. Could probably speed things up a bit for you (as well as be safer than calling exec).

If you need any help integrating that feel free to ping us in irc or here!

**Comment by joelgallant** [comment]
:+1:

**Comment by cloutier** [comment]
I think I should deprecate server.js instead and use ipfs web apis in PHP. It would be simpler for other people to install ipfs.pics on their own servers without any node.js. 

@whyrusleeping Do you know if there are php api bindings or should I write my own?

**Comment by MichaelMure** [comment]
https://github.com/ipfs/ipfs/issues/83

The answer seems to be no.

**Comment by cloutier** [comment]
@MichaelMure Thanks!

I'm going to write my own. I'll keep it in a separate module to help people who want to reuse it.

**Comment by cloutier** [comment]
@whyrusleeping I am having trouble implementing ipfs add. I tried:

```
http://127.0.0.1:5001/api/v0/add?arg=/home/Vincent/Pictures/test/test.png
http://127.0.0.1:5001/api/v0/add?path=/home/Vincent/Pictures/test/test.png
http://127.0.0.1:5001/api/v0/add/home/Vincent/Pictures/test/test.png
```

I always get this error:

```
File argument 'path' is required
```

**Comment by cloutier** [comment]
@whyrusleeping Nevermind, [I was doing it wrong](https://github.com/ipfs/js-ipfs-api#add).

**Comment by cloutier** [comment]
Thanks for the suggestion, ipfs.pics is now much faster and the code is more readable! :+1: 

I only implemented the subset of ipfs commands we needed, if someone needs a particuliar command, it would be my pleasure to add it. Just ping me.

**Comment by cloutier** [comment]
@arvidj : With this the upload folder is not needed anymore. I've removed this step in the wiki.

**Comment by shgandhi** [comment]
@cloutier : I am getting the same error `File argument 'path' is required` when implementing ipfs add. Can you please point the right way for doing that?

**Comment by cloutier** [comment]
[Sure!](https://github.com/ipfspics/ipfspics-server/blob/cf0422332f3b2af506fafed6ba6992432bc79260/app/class/ipfs.class.php#L37)

If I remember right (it's been a while), I had the same error until I added the `stream-channels=true`.
