### ISSUE TITLE
TLS certificate

### ISSUE THREAD

**Issue by gellenburg** [ipfspics/server#16]
This needs to be TLS (SSL)/ HTTPS. At the very least, set up a self-signed cert on your server and get a CloudFlare account with SSL. All generated URLs should be https URLs too to avoid potentially breaking any site that the images are embedded in.

**Comment by victorb** [comment]
You can always go via the public gateway setup by the people behind IPFS.
So if your image hash is `QmW3FgNGeD46kHEryFUw1ftEUqRw254WkKxYeKaouz7DJA`, you'll load the image by including `<img src="https://ipfs.io/ipfs/QmW3FgNGeD46kHEryFUw1ftEUqRw254WkKxYeKaouz7DJA"/>`

Free https :)

**Comment by gellenburg** [comment]
Which would be fine if the embed and linking instructions linked to https://ipfs.io/ipfs/ instead of http://ipfs.pics/

![screenshot_12](https://cloud.githubusercontent.com/assets/7026750/10712248/b8de6d96-7a62-11e5-92d0-73edf2fe4a02.png)

**Comment by cloutier** [comment]
@VictorBjelkholm I feel like it would be leeching bandwith from a community resource. I think I will go with standard SSL, maybe with a [free certificate](https://www.startssl.com/) or with Cloudflare. 

I will work on this right after fixing #10 and #12.

**Comment by cloutier** [comment]
We went with a standard paid certificate. Everything should work fine now under https and I will close this issue in a day or two if we don't find any problem.
