### ISSUE TITLE
Advantage popular pictures in the random feature

### ISSUE THREAD

**Issue by didiercf** [ipfspics/server#23]
Need to a write query that would advantage the pictures with the most upvotes in the random feature without making them the exclusive content shown.

**Comment by arvidj** [comment]
Simple idea: Create a list with all known hashes, in such a way that each hash appears X times, where X = votes + 1 for that hash. So if there are three hashes: A, B and C with 2, 1 and 0 votes respectively, the list would be: [A,A,A,B,B,C]. Then pick a random element out of this list. This would probably not be fair though. Here is some more inspiration: http://www.evanmiller.org/how-not-to-sort-by-average-rating.html

**Comment by didiercf** [comment]
On another part of the problem, I'll most likely use a virtual table (CREATE VIEW) to combine both our current tables and make the vote count easier.

**Comment by cloutier** [comment]
Another idea: 

```
 x = the number of hashes 
 y = a random humber between 0 and x^2
 the selected hash is the one in position closest to sqrt(y) when they are 
 reverse-ordered by (upvotes - downvotes)
```

It should be a very fast query. It won't advantage much the best one though, but having some bad ones should be an aspect of a random pictures. 

@arvidj's link could be very good for a best-of page.
