### ISSUE TITLE
The file pic.php is not used

### ISSUE THREAD

**Issue by arvidj** [ipfspics/server#26]
Seems like this file is not referenced anywhere, can be removed right?

**Comment by cloutier** [comment]
It is a [wrapper](https://github.com/ipfspics/server/blob/master/app/.htaccess#L3) arround ipfs to send caching header. It is not obligatory, but it makes loading waaaay faster. I will also make it not load images that were banned in the db.

**Comment by arvidj** [comment]
Ah ok, I missed the reference in .htaccess.
