### ISSUE TITLE
Automatic failover

### ISSUE THREAD

**Issue by cloutier** [ipfspics/server#27]
ipfs.pics should automatically detect if our ipfs node is down, and then try to load images from ipfs.io.

[Html5 offline apis](http://diveintohtml5.info/offline.html) could be also used.

**Comment by victorb** [comment]
If I upload an image to ipfs.pics, you're just storing it on the node there, right? So if that node goes down, and other nodes haven't already replicated the image, you're not gonna be able to get it from the gateway either.

**Comment by cloutier** [comment]
We are not just storing it on our server. @didiercf has made a replication tool that pins everything uploaded to our server on our computers. He is reworking it in a way that will allow anyone to easily backup any ipfs.pics server easily. It's true that we will have to make sure at least one of our computer running all the time though.
