### ISSUE TITLE
PNG files do not display correctly

### ISSUE THREAD

**Issue by starrychloe** [ipfspics/server#28]
PNG files don't display.

http://ipfs.pics/QmahoGMbbawakfazHfCaFYsVhGkkMPqMYQcTiqe5HxYbBE

**Comment by didiercf** [comment]
They seem to be working for me. Which browser are you using?

**Comment by didiercf** [comment]
It seems there was a problem this morning where pictures in general wouldn't work, it should work now.

**Comment by starrychloe** [comment]
I'm using Chrome on Windows.
