### ISSUE TITLE
keyboard shortcuts

### ISSUE THREAD

**Issue by jbenet** [ipfspics/server#4]
- `r` - random

Looooove the random feature. addicting :)  :heart:

**Comment by cloutier** [comment]
Thank you :+1: 

Also
- `u` for upvotes
- `d` for downvotes

**Comment by cloutier** [comment]
We should also inform people that they can press r for a random picture. We could make something inspired by github's protips:
![github protip](https://cloud.githubusercontent.com/assets/1014864/10900295/ea5a7518-81ab-11e5-880f-c84f759ecbd5.png)

**Comment by jbenet** [comment]
~~@cloutier can we have one for random?~~ disregard. just saw it
