### ISSUE TITLE
update ipfs

### ISSUE THREAD

**Issue by chpio** [ipfspics/server#40]
ipfs was updated to v0.4 recently. (https://ipfs.io/blog/14-ipfs-0-4-0-released)

ipfs.pics seams to run an old version... yet :)

> Running ipfs version 0.3.10

**Comment by didiercf** [comment]
It is now done! Proudly running 0.4.0!

**Comment by cloutier** [comment]
Seems like pins are not kept during an upgrade, we are currently restoring from a backup

**Comment by cloutier** [comment]
I made sure to keep old pics, everything should work fine now!
