### ISSUE TITLE
rename the repo

### ISSUE THREAD

**Issue by chpio** [ipfspics/server#41]
hi,

i think the repo name should be prefixed with a "ipfspics-" or something.
- if you fork it you end up with a meaningless "server" repo.
- the same for cloning (there is the possibility to set the name before cloning it; not very serious)

**Comment by cloutier** [comment]
I think in hindsight it would have been a good idea, but benefits are small. You can change the name of any forks you make and you can change the folder's name after cloning. It would also break all the git origins out there. 

@didiercf What is your take on it?

**Comment by chpio** [comment]
didn't know you can rename a forked repo... :)

> It would also break all the git origins out there.

gh redirects to the new location. wouldn't be a problem (imho)

**Comment by cloutier** [comment]
Oh I didn't know github redirected, that would make it okay in my book, let me make some tests first.

**Comment by cloutier** [comment]
Made some test and you were right. I renamed the repo.

Thanks for the suggestion!
