### ISSUE TITLE
Reddit thumbnail and expando support

### ISSUE THREAD

**Issue by leethax666** [ipfspics/server#43]
Posts to reddit should have a correct thumbnail that can expand to the full image with reddit/RES

Image pages should perhaps include linkbacks to the reddit comments for the post.

**Comment by cloutier** [comment]
I think RES has to integrate us, and not the other way around. We already have every embed meta tag, except for the oEmbed standard, but I couldn't find anything about reddit support for oEmbed. 

I know Wordpress has an api called [Pingback](https://en.support.wordpress.com/comments/pingbacks/) that we could integrate. I am not sure if reddit has this, or something equivalent.

**Comment by leethax666** [comment]
I did I better search, and thumbnails are showing for other ipfs.pics submissions, so maybe mine was just messing up for some reason. Pingback could be useful but I think it deserves a separate issue
