### ISSUE TITLE
Mime type for WMV screencasts wrong - just says 'document'

### ISSUE THREAD

**Issue by starrychloe** [ipfspics/server#45]
When trying to view a screencast, it shows the video as a broken picture.
https://ipfs.pics/QmVR1vgRiXeq9PsYz62TSvH3ngUX4obVLasKbfEDXnvsFD

Even when linked directly, it sets the mime type wrong. It shows 'document' in Chrome Network tab, and the header says 'Content-Type:image/png'.
https://ipfs.pics/ipfs/QmVR1vgRiXeq9PsYz62TSvH3ngUX4obVLasKbfEDXnvsFD

I uploaded through ipfs.pics fine and it downloads fine, if I save it with the right extension.

**Comment by cloutier** [comment]
We don't support video on ipfs.pics for multiple reasons (including much bigger storage cost). We remove everything that is not a picture, but this process is not yet automated. 

I recommend that you add your video content on a computer that you own with IPFS installed.

**Comment by starrychloe** [comment]
But it's only 766kb, smaller than many images! Even if I added it locally, I can't share it with tech support via link since it doesn't display correctly. (Doubt they have IPFS installed.)
