### ISSUE TITLE
Can't see any pics.

### ISSUE THREAD

**Issue by Snarkly** [ipfspics/server#47]
I can go here https://ipfs.pics/ and then click on random, trending and best but all I get is a white screen, no pictures show. It just started doing this day or two ago. I also tried to upload and image and I got the white screen again.

**Comment by cloutier** [comment]
Fixed. We are having problem with this server, and I'll be migrating ipfs.pics to a new one this weekend, and it should solve everything once and for all.

Thanks for reporting it :smile:
