### ISSUE TITLE
Videos

### ISSUE THREAD

**Issue by nixoye** [ipfspics/server#9]
When can webm be supported?

**Comment by cloutier** [comment]
It's in our todo list, but quite far down. Videos are quite larger and more complex (because of all the different codecs). We want to get the basics right before tackling that.

So to answer your question:    Soon :tm:

**Comment by cloutier** [comment]
With the TPP getting signed soon, we would be sued for a lot for copyright infringment, so I am not going to implement videos...

**Comment by balupton** [comment]
There are plenty of legit reasons for video on ipfs, such as sharing videos with family, or hosting ones own professional videos to share with your own large audience
